name: add files to release

on:
  # allows us to run workflows manually
  workflow_dispatch:

  release:
    types: # This configuration does not affect the page_build event above
      - published
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  building-plugin:
    runs-on: ubuntu-latest

    name: 'create_files'

    container:
      image: shimwell/design_automator

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: install package
        run: |
          pip install .

      - name: create files
        run: |
          python example_simulation_cad.py
          python update_readme.py
          apt-get -y update
          apt-get -y install zip
          zip attached_files.zip *.stp *.png *.json *.xml *.h5m *.md

      - name: Upload artifact for CI
        uses: actions/upload-artifact@v2
        with:
          name: attached_files.zip
          path: attached_files.zip
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 

      - name: Upload files into the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: attached_files.zip
          asset_name: attached_files.zip
          tag: ${{ github.ref }}
