name: TBR improvements

on:
  pull_request:
    branches:
      - develop
      - main


jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: shimwell/design_automator
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package
        run: |
          pip install .
          python -c "import design_automator"
      - name: Run cad creation tests
        run: |
          pip install .[tests]
          pytest tests/test_dagmc_creation.py -v
      - name: Run neutronics tests
        run: |
          pytest tests/test_improvement_tbr.py -v
