name: update readme

on:  
  pull_request:    
    branches:
    - main  
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shimwell/design_automator
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: install package
        run: |
          pip install .
      - name: Generate new CAD values and neutronics values
        run: |
          python example_simulation.py
          apt-get install -y imagemagick
          convert current_design.svg current_design.png
          python plot_improvements.py
      - name: update_readme_from_template
        run: |
            python update_readme.py
      - name: Commit files
        run: |
          git status
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add current_design.png
          git add current_design.stp
          git add neutron_heating_xy.png 
          git add improvements_*.png 
          git add design_successful.json
          git add README.md
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
